# Generated by Django 4.2.23 on 2025-07-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('material', 'Material Sample'), ('biological', 'Biological Sample'), ('sensor', 'Sensor Footage'), ('image', 'Image/Photo'), ('other', 'Other')], default='other', max_length=50)),
                ('date_observed', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
