# Generated by Django 4.2.23 on 2025-08-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
