# Generated by Django 4.2.23 on 2025-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_videosource_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
