# Generated by Django 4.2.23 on 2025-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_videosource_last_fetched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_run_started', models.DateTimeField(blank=True, null=True)),
                ('last_success_any', models.DateTimeField(blank=True, null=True)),
                ('last_success_with_new', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
