# Generated by Django 4.2.23 on 2025-07-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('is_uap_related', models.BooleanField(default=True)),
                ('source_link', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
