# Generated by Django 4.2.23 on 2025-07-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('source_links', models.TextField(blank=True, help_text='Newline-separated URLs')),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
