# Generated by Django 4.2.23 on 2025-07-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisclosureSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_government_official', models.BooleanField(default=False)),
                ('is_military', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DisclosureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('hearing', 'Congressional Hearing'), ('interview', 'Interview'), ('press', 'Press Conference'), ('leak', 'Leaked Testimony or Memo'), ('statement', 'Public Statement'), ('article', 'Published Article'), ('other', 'Other')], default='other', max_length=30)),
                ('source_link', models.URLField(blank=True, help_text='Link to article, transcript, or media')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags (e.g., NHI, crash retrieval)', max_length=255)),
                ('source', models.ManyToManyField(related_name='events', to='disclosure.disclosuresource')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DisclosureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='disclosure.disclosureevent')),
            ],
        ),
        migrations.CreateModel(
            name='DisclosureClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_direct_quote', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='disclosure.disclosureevent')),
            ],
        ),
    ]
